default:
  DBNAME: 'alex'
  DBUSER: 'alex'
  DBHOST: '82.146.58.45'
  DBPASS: '7F3yr98!'
  PSTOKEN: 'AIzaSyBBPIg9RhqhPfZFNiwtNqVaijZiUJCUKkc'
  TGTOKEN: '1124233516:AAGM_htHVW95qXsQzb0C8e3zE1TGsi2u6nI'
